/*
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * OpenAPI spec version: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
// ORIGINALY FOUND IN TS 29571
package io.swagger2.model;

/**
* AnyOfTaiRm
*/
public interface AnyOfTaiRm {

}
