/*
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * OpenAPI spec version: 1.2.0-alpha.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
// ORIGINALY FOUND IN TS29512 NpcfSMPolicyControl
package io.swagger2.model;

/**
* AnyOfFlowDirectionRm
*/
public interface AnyOfFlowDirectionRm {

}
